# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 135b101b51d1ae9bca38e593e11066381775d97d3862becd7ce4fdf040ba31910492914c5704d27348a3135699cc3dbb4266062cc9702c3c5e70dfe5ea933f7b

test:
  secret_key_base: b850c58964e4d8f05521284d60f341a40acc66de69b5aeb820d922cc32c825c7e3f502c6ad88952e71aa4af5ee3f960d7234608a19347815ea3e13a776a6502f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
